"""modify column length

Revision ID: ede1802067f0
Revises: 
Create Date: 2020-05-01 21:25:20.897303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ede1802067f0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('travel_info',
    sa.Column('contentID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('addr', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('img', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('overview', mysql.VARCHAR(length=2000), nullable=False),
    sa.PrimaryKeyConstraint('contentID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_info')
    # ### end Alembic commands ###
